language: node_js
node_js: 
  - "11"

# Codecov setup

install:
  - npm install -g codecov
  - npm install -g istanbul
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
  - codecov