/*
 *
 * Robot constants
 *
 */

export const TOKEN_VERIFICATION_INITIATED = 'app/Robot/TOKEN_VERIFICATION_INITIATED';
export const TOKEN_VERIFICATION_SUCCESSFUL = 'app/Robot/TOKEN_VERIFICATION_SUCCESSFUL';
export const TOKEN_VERIFICATION_FAILED = 'app/Robot/TOKEN_VERIFICATION_FAILED';

export const BUNDLE_PUBLISHING_INITIATED = 'app/Robot/BUNDLE_PUBLISHING_INITIATED';
export const BUNDLE_PUBLISHING_SUCCESSFUL = 'app/Robot/BUNDLE_PUBLISHING_SUCCESSFUL';
export const BUNDLE_PUBLISHING_FAILED = 'app/Robot/BUNDLE_PUBLISHING_FAILED';

export const SET_BUNDLE_ID = 'app/Robot/SET_BUNDLE_ID';
