const CONSTANTS = {
	START_BUNDLE: 'START_BUNDLE',
	ADD_RESOURCE: 'ADD_RESOURCE',
	REMOVE_RESOURCE: 'REMOVE_RESOURCE',
	UPDATE_RESOURCE: 'UPDATE_RESOURCE',
	SET_ACTIVE_RESOURCE: 'SET_ACTIVE_RESOURCE',
	SET_ACTIVE_RESOURCE_ID: 'SET_ACTIVE_RESOURCE_ID',
	SET_EDIT_ACTIVE_RESOURCE: 'SET_EDIT_ACTIVE_RESOURCE',
	STORE_BUNDLE: 'STORE_BUNDLE'
}

export default CONSTANTS;